apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uvtp5tep5-nodejs 
  janus-idp.io/tekton: uvtp5tep5-nodejs
  backstage.io/kubernetes-id: uvtp5tep5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uvtp5tep5-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  