apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uvtp5tep5-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uvtp5tep5-nodejs 
  name: uvtp5tep5-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uvtp5tep5-nodejs 
